[Interface]
PrivateKey = __WG_PRIVATE_KEY__
Address = __WG_CLIENT_ADDRESS__
DNS = __WG_DNS__

[Peer]
PublicKey = __WG_SERVER_PUBLIC_KEY__
PresharedKey = __WG_PRESHARED_KEY__
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = __SERVER__:__WG_SERVER_PORT__
PersistentKeepalive = 25
Jc = __AWG_JC__
Jmin = __AWG_JMIN__
Jmax = __AWG_JMAX__
S1 = __AWG_S1__
S2 = __AWG_S2__
H1 = __AWG_H1__
H2 = __AWG_H2__
H3 = __AWG_H3__
H4 = __AWG_H4__
